### ISSUE TITLE
Game is crashing on Fabric 1.21.1

### ISSUE THREAD

**Issue by appztr4ckt** [Lncvrt/chat-clear-plus#1]
Client Log: https://mclo.gs/89sTzte

**Comment by Lncvrt** [comment]
I'll look into this soon

**Comment by Lncvrt** [comment]
> Client Log: https://mclo.gs/89sTzte

Could be either a mod compatibility or java 21.Try uninstalling some mods or make a new prism profile

**Comment by appztr4ckt** [comment]
thanks for nothing.

**Comment by Lncvrt** [comment]
> thanks for nothing.

you aren't trying to provide any helpful information, like even making a fresh instance with no mods
